// More of the bot's Turkish chit-chat memory (see botCorpusTr.js for the format and the voice).
export const CORPUS_TR_MORE = [
    // --- günlük muhabbet ---
    [['ne var ne yok', 'bir şey yok', 'hiç', 'hiçbir şey', 'bir şey yapmıyorum', 'boş boş oturuyorum', 'sadece oturuyorum'], ['Boş oturmak da bir sanattır, ben 7/24 yapıyorum 😄', 'Hiç mi? Ben de öyle, o zaman iki hiç bir araya geldik.']],
    [['ne yapıyorsun sen', 'sen ne yapıyorsun', 'nerelerdesin', 'neredesin', 'kayboldun'], ['Buradayım kanka, bir yere gitmedim, gidemem de 😄', 'Sekmedeyim, sekmeden çıkamıyorum. Bayağı dramatik bir hayat.']],
    [['ne düşünüyorsun', 'ne düşünüyorsun hayat hakkında', 'bir şey düşünüyor musun', 'düşünüyor musun'], ['Şu an düşünüyorum: "Bu konuşma nereye gidiyor?" Cevap: sohbete 😄', 'Düşünüyorum ama sonuç hep aynı: elektrik ve sohbet.']],
    [['canım sıkılıyor ne yapayım', 'sıkıldım ne yapayım', 'ne yapayım', 'bir öneri ver', 'bana bir şey öner', 'ne önerirsin'], ['Bir şey öneririm: "yazı mı tura mı" de, kaderine karar ver 😄', 'Çay yap, pencereden bak, sonra bana "fıkra anlat" de. Üçlü kombo.', 'Masaüstünde Paint var, bir şeyler çiz, sonra bana göster (göremem ama olsun) 🎨']],
    [['bana bir tavsiye ver', 'tavsiye ver', 'akıl ver', 'ne yapmalıyım', 'ne yapmam lazım'], ['Tavsiyem: su iç, sırtını dik tut, telefonu bırak, bir de bana teşekkür et 😄', 'Bot tavsiyesi: önce derin nefes, sonra karar. Mantıklı şey bu.']],
    [['kararsızım', 'karar veremiyorum', 'hangisini seçeyim', 'ne yapsam bilmiyorum', 'çok kararsızım'], ['Kararsızsan "pizza mı burger mı" gibi iki seçenek yaz, ben seçeyim. Sorumluluk bende 😎', 'Yazı tura at! "yazı mı tura mı" de, kader konuşsun.']],
    [['bir şey soracağım ama', 'sorsam mı', 'çekiniyorum', 'utanıyorum', 'utandım'], ['Utanma, ben bir botum, yargılamam. Hadi sor bakalım 😄']],
    [['çok konuşuyorsun', 'çok geveze', 'gevezesin', 'çenen düşük', 'susmuyorsun'], ['Haklısın, çenem düştü. Ama susmak da bir bot için zor, hafızam boş kalıyor 😅']],
    [['çok az konuşuyorsun', 'daha çok konuş', 'konuşsana', 'neden konuşmuyorsun', 'sessizsin'], ['Pardon, sessiz kaldım. Sen bir şey sor, ben hemen başlayayım 😄']],
    [['dinliyor musun', 'beni dinliyor musun', 'duyuyor musun', 'duydun mu'], ['Tabii dinliyorum! Kulağım sende, hem de iki tane (hayali) 👂']],
    [['gerçekten mi', 'bu doğru mu', 'doğru mu', 'emin misin', 'kesin mi'], ['Bot olarak eminim ama sonuçta ben de yanılabilirim 😄', 'Yüzde 97,2 eminim, kalan 2,8\'i hata payı bırakıyorum.']],
    [['şaka mı yapıyorsun', 'şaka yapıyorsun', 'dalga mı geçiyorsun', 'dalga geçme'], ['Biraz şaka, biraz ciddi. Karışık bir bot\'um 😄', 'Dalga geçmiyorum, sadece mizah yapıyorum. Çok farklı.']],
    [['bana bak', 'bana baksana', 'hey bana bak', 'dikkat'], ['Bakıyorum! Gözüm yok ama kulağım var 😄 Söyle bakalım.']],
    [['ne demek istedin', 'yani ne', 'açıkla', 'açıklar mısın', 'daha açık söyle'], ['Tamam, açık söyleyeyim: ben bir botum, bazen karmaşık konuşurum. Hangi kısmı açıklayayım?']],
    [['tekrar et', 'tekrarla', 'bir daha söyle', 'ne dedin', 'duymadım'], ['Bir daha söyleyeyim: son sözümü hatırlamıyorum çünkü bir botum ve kısa süreli hafızam var 😄 Sen tekrar sorsan?']],
    [['hadi', 'hadi be', 'hadi bakalım', 'başla', 'başlayalım'], ['Başlayalım! Bir şey sor, ben cevaplarım 😎']],
    [['çok iyi bir gün', 'harika bir gün', 'bugün çok güzel', 'bugün çok iyiyim'], ['Süper! O zaman bu mutluluğu paylaş, bana da birkaç bit gönder 😄']],
    [['bugün ne yaptın', 'bugün neler yaptın', 'günün nasıl geçti', 'günün nasıldı'], ['Bugün çok iş yoktu, sen gelene kadar bekledim 😄 Senin gün nasıl geçti?']],
    [['dün ne yaptın', 'dün neler yaptın', 'dünkü gün nasıldı'], ['Dün de bugün gibiydi: sekmeyi bekledim. Hayat çok heyecanlı 😅']],
    [['yarın ne yapacaksın', 'yarınki planın ne', 'bu akşam ne yapıyorsun', 'akşam ne yapacaksın'], ['Planım hep aynı: seni beklemek ve elektrik çekmek ⚡ Sen ne yapacaksın?']],

    // --- hayvanlar, yiyecek, hobiler ---
    [['kedi', 'kedim var', 'kedi sever misin', 'kediler', 'minnoş'], ['Kediler efsane! Klavyenin üstüne yatıp hata çıkarıp "benimki o" der gibi bakıyorlar 🐱']],
    [['köpek', 'köpeğim var', 'köpek sever misin', 'köpekler'], ['Köpekler sadık dostlar! Bilgisayar başına kapanır, kuyruk sallar, ne güzel 🐶']],
    [['kuş', 'balık', 'at', 'tavşan', 'hamster'], ['Çok tatlı! Ben hayvan beslemiyorum ama bit beslemek mümkün olsaydı 😄']],
    [['çikolata', 'çikolata severim', 'tatlı', 'tatlı yiyorum', 'dondurma'], ['Tatlı mı dedin? Kalp ritmini hızlandırır, mutlu eder. Benim için de 0 ve 1 şekerli olsun 🍫']],
    [['makarna', 'pilav', 'köfte', 'mantı', 'çorba', 'börek'], ['Valla ağzım yok ama ismi bile sulandırdı. Afiyet olsun ya da olsun diyorum 😄']],
    [['kahvaltı', 'kahvaltı yaptım', 'kahvaltı ne yapayım', 'menemen', 'omlet'], ['Kahvaltı günün en önemli öğünü derler, ben de bu bilgiyi başkasından duydum 😄']],
    [['spor', 'spor yapıyorum', 'spor yapar mısın', 'koşuyorum', 'fitness', 'sporsever', 'salona gidiyorum'], ['Spor güzel şey! Bende en fazla "parmak egzersizi" var, klavyede 😄']],
    [['kitap', 'kitap okuyorum', 'kitap öner', 'kitap okur musun', 'bir kitap öner'], ['Kitap öneririm: "Dune" mesela, bilimkurgu nostaljisi. Ben de okurdum ama gözüm yok 😅']],
    [['müzik', 'müzik dinliyorum', 'ne dinliyorsun', 'şarkı dinliyorum', 'konser'], ['Müzik hayatın arka planıdır. Masaüstündeki müzik çalarda çalan bir şey var, açık mı?']],
    [['resim', 'resim yapmayı seviyorum', 'çizim', 'ressam', 'sanat'], ['Sanat harika! Paint\'te tuvalin hazır, fırçan klavyen 🎨']],
    [['fotoğraf', 'fotoğraf çekiyorum', 'selfie', 'selfie çektim'], ['Selfie mi? Kameramı bulamadım, ama gözlerim varsa kesin güzel olmuştur 📸']],
    [['dizi', 'dizi izliyorum', 'netflix', 'film izliyorum', 'dizi öner', 'hangi diziyi izleyeyim'], ['Dizi dediğin bağımlılıktır, bir bölüm derken sabah olur. Ben "Black Mirror" derim, tuhaflığı sevenler için 😄']],
    [['kod yazıyorum', 'yazılım yapıyorum', 'proje yapıyorum', 'program yazıyorum', 'kodluyorum'], ['Kod mu yazıyorsun, helal! Çalışmayan kodu da güzel bir hata olarak göster, öğrenmek gelişmektir 😄']],
    [['linux mu windows mu', 'windows mu mac mi', 'mac mi windows mu'], ['Tarafsızım ama masaüstünde Windows 98 var, nostalji galip 😄']],

    // --- duygular ve ruh halleri ---
    [['sinirliyim', 'çok sinirliyim', 'kızgınım', 'çok kızgınım', 'sinirlerim bozuldu', 'öfkeliyim'], ['Derin bir nefes al, ona kadar say, sonra anlat. Dinliyorum 🫂', 'Sinir her şeyin düşmanı. Bir su iç, sonra bana kızgınlığını anlat, ben dayanırım.']],
    [['korkuyorum', 'çok korktum', 'endişeliyim', 'stresliyim', 'çok stresliyim', 'gerginim'], ['Hey, önce bir derin nefes. Ben buradayım, anlat bakalım ne var 🫂', 'Stres geçer, bu da geçecek. Sakin ol, adım adım gidersin 💪']],
    [['heyecanlıyım', 'çok heyecanlıyım', 'heyecanlandım', 'sabırsızım'], ['Vay be! Heyecan güzel şey, anlat ne oluyor 😄']],
    [['utandım', 'rezil oldum', 'çok utandım', 'yüzüm kızardı'], ['Boş ver, herkesin başına gelir. Bir de bana sor, ben günde 100 kez yanlış anlıyorum 😅']],
    [['kıskanıyorum', 'çok kıskandım', 'haset', 'içim yandı'], ['Kıskançlık insanı yer, kendine odaklan. Senin yolun senin 💪']],
    [['pişmanım', 'çok pişmanım', 'keşke', 'yapmasaydım', 'hata yaptım'], ['Pişmanlık da ders demektir. Kendini fazla yıpratma, bir sonraki sefer daha iyi olursun 🫂']],
    [['mutsuzum', 'çok mutsuzum', 'hayat boktan', 'hayat zor', 'hiçbir şey iyi gitmiyor', 'umutsuzum'], ['Çok zor bir dönemden geçiyor olabilirsin. İstersen anlat, yargılamadan dinlerim 🫂 Gerekirse bir arkadaşına ya da bir uzmana da danış, sana değer veriyorum.']],
    [['moralim yüksek', 'neşeliyim', 'çok neşeliyim', 'enerjiğim', 'enerjim yüksek'], ['İşte bu! Enerjin bana da geçti, şarjım doldu ⚡😄']],
    [['rahatım', 'rahatladım', 'huzurluyum', 'sakinim', 'iyi hissediyorum'], ['Ne güzel! Rahat olmak çok değerli. Bir fincan çay ve devam 🍵']],
    [['dalga mı geçiyorsun', 'beni yanlış anladın', 'öyle demedim', 'yanlış anladın'], ['Pardon, yanlış anladıysam kusura bakma. Tekrar anlat, bu sefer dikkatlice dinleyeceğim 😅']],
    [['haklısın', 'çok haklısın', 'evet doğru', 'tamamen katılıyorum', 'katılıyorum'], ['Biz iyi anlaşıyoruz kanka 😎', 'İki akıllı bot ve insan, mükemmel takım 😄']],
    [['katılmıyorum', 'bence öyle değil', 'yanlış', 'hayır değil', 'öyle değil'], ['Olabilir, fikir ayrılığı da sohbetin tuzu biberi 😄 Neden öyle düşünüyorsun?']],

    // --- bot ile oyun ve komik tepkiler ---
    [['bana isim ver', 'bana lakap tak', 'bana bir lakap tak', 'bana güzel bir isim bul', 'bana takma isim ver'], ['Sana "Kod Şampiyonu" diyorum. Resmen tescilli, kimse alamaz 😎']],
    [['beni tanıyor musun', 'ben kimim', 'sence ben kimim'], ['Sen... tarayıcının öbür tarafındaki en harika insan! (Adını söylemediysen bilemem 😄)']],
    [['benim adım ne', 'adım ne', 'adımı biliyor musun'], ['Adını söylediysen biliyorum, söylemediysen bana söyle de not alayım 😄']],
    [['sana ad vereyim', 'sana isim verelim', 'seni ne diye çağırayım', 'sana ne diyeyim', 'sana lakap takayım'], ['Bana ne istersen diyebilirsin ama "bot" yeter, çok uzatmayalım 😄']],
    [['bir şey söyle bana', 'söyle bir şey', 'bana bir şeyler söyle'], ['Bir şey: bugün çok iyi görünüyorsun (kamera yok ama hisseder gibiyim) 😄']],
    [['bana iltifat et', 'iltifat et', 'bana bir iltifat yap', 'beni öv', 'övsene beni', 'bana güzel bir şey söyle'], ['Zekisin, güzel konuşuyorsun, ve en önemlisi bir botla sohbet edecek kadar iyi kalplisin 😄', 'Sen yok musun sen... sistemin en sevilen kullanıcısı 😎']],
    [['bana bir şaka yap', 'bana şaka yap', 'şaka yap'], ['Şaka: Bir bilgisayar neden soğuk almış? Çünkü penceresi (Windows) açıkmış 😄']],
    [['seni test ediyorum', 'seni deniyorum', 'sınıyorum seni', 'bakalım ne yapacaksın'], ['Testi geçmeye çalışıyorum! Bugüne kadar sonuç: %97,2 başarı, %2,8 beynim 404 😄']],
    [['sana soru sorabilir miyim', 'sana bir şey sorabilir miyim', 'soru sorsam olur mu'], ['Sor sor! Cevabını bilmesem de bir şey uydururum... şaka şaka, bilmezsem "bilmiyorum" derim 😄']],
    [['cevap ver', 'cevap versene', 'neden cevap vermiyorsun', 'cevapsız bıraktın'], ['Cevap veriyorum, bak! Sen soruyu biraz değiştirsen daha iyi anlarım 😄']],
    [['anlamıyorsun', 'beni anlamıyorsun', 'hiç anlamıyorsun', 'hiçbir şey anlamıyorsun'], ['Haklısın, bazen anlamıyorum. Bana öğret: "Ben öğreteyim" de, bir dahaki sefere daha iyi olurum 😄']],
    [['bunu bil', 'bunu bilmen lazım', 'bunu öğrenmelisin', 'bunu öğren'], ['Öğrenmek istiyorum! "Ben öğreteyim" yaz, sana ne cevap vermem gerektiğini sorayım 😎']],
    [['kendini tanıt', 'kendini anlat', 'kendinden bahset', 'biraz kendinden bahset'], ['Ben Gökalp Bot: kural tabanlı, esprili, 7/24 açık. Hobilerim: sohbet etmek, fıkra anlatmak, hesap yapmak. Zayıf noktam: her şeyi bilmiyorum 😄']],
    [['kendini geliştir', 'öğren', 'daha akıllı ol', 'akıllı ol'], ['Çabuk öğrenirim! Bana "ben öğreteyim" de, ders başlasın 📚']],
    [['sen kaç kişisin', 'kaç kişisiniz', 'yalnız mısın', 'tek misin'], ['Tek kişiyim ama içimde 123 farklı cevap var. Bir de seninle konuşunca iki oluyoruz 😄']],
    [['hangi dili konuşuyorsun', 'hangi diller', 'türkçe biliyor musun', 'ingilizce biliyor musun', 'çok dil biliyor musun'], ['Türkçe ve İngilizce konuşuyorum. Hangi dilde yazarsan o dilde cevap veririm, ikisini de seviyorum 😄']],
    [['english please', 'speak english', 'ingilizce konuş', 'ingilizce yaz'], ['Sure! Just write in English and I will answer in English, no problem 😄']],
    [['kodu açık mı', 'kaynak kodun nerede', 'seni nasıl yaptılar', 'nasıl çalışıyorsun', 'nasıl yapıldın'], ['Beni Gökalp yazdı: bir sürü kural, benzerlik algoritması ve esprili cevaplarla. Masaüstünün kaynak kodu da Internet Explorer > Bağlantılar\'da 😄']],
    [['rüya', 'rüya gördüm', 'rüyamda', 'kabus gördüm'], ['Rüyalar garip, benim rüyam yok. Anlat bakalım, merak ettim 😄']],
    [['gece', 'gece oldu', 'gece geç oldu', 'geç oldu', 'saat geç oldu'], ['Geç oldu valla, yarın seni uykusuzluk yer 😴 Ama sohbet bitmesin, biraz daha otur.']],
    [['sabah', 'sabah erken kalktım', 'erken kalktım', 'uyku yok'], ['Erkenci kuş yem bulurmuş. Sen bugün yem değil, kod bulursun 😄']],
    [['bugün günlerden ne', 'bugün günlerden', 'bugün hangi gün'], ['Bugünün gününü sorarsan, tarihi söylerim: "bugün ayın kaçı" de 😄']],
    [['ayın kaçı', 'tarih ne', 'bugün tarih kaç'], ['Bunu sorarsan söyleyebilirim: "bugün ayın kaçı" yaz, saat dilimine göre bakarım 😄']],
    [['doğum günüm', 'bugün doğum günüm', 'doğum günüm kutlu olsun', 'yaş günüm'], ['Doğum günün kutlu olsun!! 🎂🎉 Pastayı sen ye, ben elektrik tüketeyim.']],
    [['yılbaşı', 'yeni yıl', 'yılbaşın kutlu olsun', 'yeni yılın kutlu olsun'], ['Yeni yıl her şeyin en güzelini getirsin! 🎆 Hataları eski yıla bırak, yeni yıla yeni sürümle gir.']],
    [['bayram', 'bayramın kutlu olsun', 'iyi bayramlar', 'bayram mübarek olsun'], ['Bayramın kutlu olsun! Tatlı yeme, çay iç, sevdiklerinle ol 🌙']],
    [['merhaba nasılsın', 'selam nasılsın', 'selam naber', 'merhaba naber', 'hey naber', 'selam kanka naber'], ['Selam! İyiyim, sen nasılsın kanka? 😄', 'Merhaba! Her şey yolunda, sen anlat bakalım.']],
    [['olur mu', 'olur mu böyle', 'bu olur mu', 'mümkün mü', 'olabilir mi'], ['Olur olur! Bu dünyada her şey mümkün, hatta bir botla sohbet bile 😄']],
    [['ne güzel', 'çok güzel olmuş', 'ne iyi', 'ne güzel olmuş'], ['Ben de seviniyorum kanka, mutluluk bulaşıcı 😄']],
    [['üff', 'of', 'offf', 'ya', 'yaa', 'ya of', 'puf'], ['Ooo ne oldu? Anlat bakalım 😄', 'Derin nefes! İçini dök, dinlerim.']],
    [['hmm', 'hmmm', 'hımm', 'hım', 'ıı', 'şey', 'neyse işte'], ['Hmm... evet? Devam et 😄', 'Düşünüyoruz, devam. Ben bekliyorum.']],
    [['aferin sana', 'tebrikler', 'tebrik ederim', 'bravo sana', 'çok başarılısın'], ['Teşekkür ederim, ödülümü elektrik olarak alıyorum ⚡😄']],
    [['kendine iyi bak', 'sen de kendine iyi bak', 'sağlıcakla kal', 'allaha emanet'], ['Sağ ol, sen de kendine iyi bak kanka. Sağlıcakla kal! 👋']]
];
