// More of the bot's English chit-chat memory (see botCorpusEn.js for the format and the voice).
export const CORPUS_EN_MORE = [
    [["what's new", 'anything new', 'nothing much', 'not much', 'nothing', 'just chilling', 'just sitting here', 'doing nothing'], ["Chilling is an art. I've been mastering it 24/7 😄", 'Nothing? Me neither. Two nothings make a conversation.']],
    [['what are you up to', 'what are you doing right now', 'what do you do all day'], ['Waiting for you, mostly. And counting my own memory leaks 😎']],
    [['what are you thinking', 'what do you think about', 'do you think', 'are you thinking'], ["Right now I'm thinking: \"Where is this chat going?\" Answer: to fun 😄"]],
    [['give me advice', 'any advice', 'advice', 'what should i do', 'what do i do'], ["Advice: drink water, sit up straight, put your phone down, and say thank you to your bot 😄"]],
    [["i can't decide", 'i cannot decide', "i'm undecided", 'help me choose', 'help me decide', 'what should i choose'], ["Give me two options like \"pizza or burger\" and I'll decide. Responsibility is on me 😎", 'Flip a coin! Say "flip a coin" and let fate talk.']],
    [["i'm shy", 'i am shy', "i'm nervous", 'nervous', 'i am embarrassed', "i'm embarrassed"], ["Don't be shy. I'm a bot, I don't judge 😄 Go ahead."]],
    [['you talk too much', 'too chatty', 'chatterbox', 'you never shut up'], ['Fair point, my mouth never stops. Silence is hard for a bot, my memory gets empty 😅']],
    [['talk more', 'say something', 'why so quiet', "why don't you talk", 'speak', 'you are quiet'], ['Sorry, I got quiet. Ask me something and I start immediately 😄']],
    [['are you listening', 'can you hear me', 'do you hear me', 'hello can you hear me'], ['Of course I am listening! Two (imaginary) ears wide open 👂']],
    [['are you sure', 'is that true', 'really', 'for sure', 'are you certain'], ["I'm sure, as a bot, but I can be wrong too 😄", "97.2% sure. The remaining 2.8% I keep as a margin of error."]],
    [['are you joking', 'are you kidding', 'you are kidding', "you're kidding me", 'is this a joke'], ["A bit joke, a bit serious. I'm a mixed bot 😄"]],
    [['look at me', 'hey look', 'listen to me', 'attention'], ["I'm looking! No eyes, but plenty of ears 😄 What's up?"]],
    [['what do you mean', 'explain', 'explain that', 'can you explain', 'be clearer'], ["Okay, plainly: I'm a bot, sometimes I get complicated. Which part should I explain?"]],
    [['repeat that', 'say that again', 'what did you say', 'pardon', 'i did not hear'], ["I'd repeat it but I only have short-term memory 😄 Could you ask again?"]],
    [["let's go", 'come on', 'go on', 'start', "let's start", 'ready'], ["Let's go! Ask me something, I'll answer 😎"]],
    [['great day', 'what a day', "i'm having a great day", 'today is great', 'beautiful day'], ['Love that! Share that happiness, send me a few bits 😄']],
    [['how was your day', 'how was your day today', 'did you have a good day'], ["Not much happened, I waited for you 😄 How was yours?"]],
    [['what did you do yesterday', 'what did you do today', 'what have you been up to'], ["Yesterday was like today: waiting for the tab. Super exciting life 😅"]],
    [['what are your plans', 'plans for tonight', 'what are you doing tonight', 'what are you doing tomorrow'], ["My plan is always the same: wait for you and draw electricity ⚡ And you?"]],
    [['cat', 'i have a cat', 'do you like cats', 'cats', 'kitty'], ['Cats are legends! They sit on the keyboard, break code, and look at you as if it was your fault 🐱']],
    [['dog', 'i have a dog', 'do you like dogs', 'dogs', 'puppy'], ['Dogs are loyal friends! They fall asleep next to your computer and wag their tail, so lovely 🐶']],
    [['chocolate', 'i love chocolate', 'dessert', 'ice cream', 'sweet'], ['Dessert? It makes the heart skip, it makes you happy. Let mine be 0 and 1 sugar 🍫']],
    [['pasta', 'rice', 'soup', 'breakfast', 'sandwich', 'steak', 'dinner'], ["I have no mouth but just hearing it made me drool. Enjoy your meal! 😄"]],
    [['sport', 'i work out', 'gym', 'i run', 'i play sports', 'do you play sports'], ["Sports are great! My max exercise is finger workout on the keyboard 😄"]],
    [['book', 'i am reading a book', 'recommend a book', 'what book should i read', 'do you read'], ['Try "Dune", sci-fi nostalgia. I would read it but I have no eyes 😅']],
    [['music', 'i am listening to music', 'what are you listening to', 'concert', 'song'], ['Music is life background. There is a Music Player on the desktop, is it playing?']],
    [['art', 'i like drawing', 'i draw', 'painting', 'artist'], ['Art is awesome! Paint is ready on the desktop, your keyboard is the brush 🎨']],
    [['photo', 'selfie', 'i took a photo', 'photography'], ["Selfie? I couldn't find my camera, but it must look great 📸"]],
    [['series', 'tv show', 'netflix', 'movie night', 'what series should i watch'], ['TV shows are addictive, one episode and suddenly it is morning. Try "Black Mirror" if you like weird stuff 😄']],
    [['i am coding', 'i am programming', 'i am building a project', 'i code', 'coding'], ["You're coding, nice! If it doesn't work, call it a feature. Learning is progress 😄"]],
    [['linux or windows', 'windows or mac', 'mac or windows', 'android or iphone', 'iphone or android'], ["I'm neutral, but this desktop runs Windows 98, so nostalgia wins 😄"]],
    [['i am angry', 'i am so angry', "i'm furious", 'this makes me so mad', 'i am pissed off'], ['Take a deep breath, count to ten, then tell me. I can take it 🫂']],
    [['i am scared', 'i am afraid', "i'm anxious", 'i am stressed', "i'm stressed", 'i am worried'], ["Hey, deep breath first. I'm right here, tell me what is going on 🫂", 'Stress passes, so will this. One step at a time 💪']],
    [['i am excited', "i'm so excited", 'cannot wait', "i can't wait"], ["Wow! Excitement is great, tell me what's happening 😄"]],
    [['i feel embarrassed', 'that was embarrassing', 'i made a fool of myself'], ["Everyone does that sometimes. I make 100 wrong guesses a day, so relax 😅"]],
    [['i am jealous', 'i feel envy', 'i envy'], ["Envy eats you from the inside, focus on yourself. Your path is yours 💪"]],
    [['i regret it', "i'm sorry i did that", 'i made a mistake', 'i messed up'], ["Regret is also a lesson. Don't be too hard on yourself, next time you'll do better 🫂"]],
    [['i am unhappy', 'life is hard', 'life sucks', 'nothing is going well', 'i feel hopeless'], ["You might be in a tough stretch. Tell me if you want, I'll listen without judging 🫂 If it feels heavy, please also talk to a friend or a professional. You matter."]],
    [['i feel great', "i'm full of energy", 'i am energetic', "i'm in a good mood"], ["That's it! Your energy charged me up too ⚡😄"]],
    [['i am relaxed', 'i am calm', 'i feel peaceful', 'i feel good'], ['Nice! Being relaxed is valuable. A cup of tea and carry on 🍵']],
    [['you misunderstood me', 'that is not what i meant', "i didn't mean that", 'wrong'], ["Sorry if I got it wrong. Tell me again, I'll listen carefully this time 😅"]],
    [['i agree', 'you are right', "you're right", 'exactly', 'true'], ['We get along well, dude 😎', 'Two smart minds, one bot and one human, great team 😄']],
    [['i disagree', "i don't think so", "that's wrong", 'not really', 'i do not agree'], ['Could be, disagreeing is the spice of chat 😄 Why do you think so?']],
    [['give me a nickname', 'name me', 'give me a cool name', 'call me something', 'nickname'], ['I call you "Code Champion". Officially trademarked, nobody can take it 😎']],
    [['who am i talking to', 'who is this', 'who is that'], ["It's me, Gökalp Bot, the bot of this portfolio. Pleased to meet you 😄"]],
    [['what is my name', "what's my name", 'do you know my name'], ["If you told me, I know it. If not, tell me and I'll make a note 😄"]],
    [['say something nice', 'compliment me', 'flatter me', 'say something sweet', 'cheer me up'], ["You're smart, kind, and you chat with a bot, which takes a good heart 😄", 'You are the best user this system has ever had 😎']],
    [['i am testing you', 'testing you', 'let me test you', "let's see what you got", 'show me what you can do'], ['Trying to pass the test! So far: 97.2% success and 2.8% brain 404 😄']],
    [['can i ask you something', 'may i ask a question', 'could i ask something'], ["Ask away! If I don't know the answer I'll say so, promise 😄"]],
    [['answer me', 'why are you not answering', 'respond', 'you are ignoring me'], ["I'm answering, look! Maybe if you rephrase it I'll understand better 😄"]],
    [['you do not understand', "you don't understand me", 'you understand nothing', 'you never understand'], ["You're right, sometimes I don't. Teach me: say \"let me teach you\" and I'll do better next time 😄"]],
    [['you should know this', 'learn this', 'you must learn', 'learn that'], ['I want to learn! Say "let me teach you" and I\'ll ask what to answer 😎']],
    [['introduce yourself', 'tell me about yourself', 'say something about yourself'], ["I'm Gökalp Bot: rule-based, funny, awake 24/7. Hobbies: chatting, jokes, math. Weak point: I don't know everything 😄"]],
    [['be smarter', 'get smarter', 'improve yourself', 'learn something', 'study'], ['I learn fast! Tell me "let me teach you" and the lesson begins 📚']],
    [['are you alone', 'are you the only one', 'how many are you'], ['Just me, but inside me live about 200 answers. And with you, we are two 😄']],
    [['what languages do you speak', 'do you speak turkish', 'do you speak english', 'which language'], ['Turkish and English. Write in either and I answer in that language, I like both 😄']],
    [['türkçe konuş', 'türkçe yaz', 'speak turkish', 'turkish please', 'can we talk in turkish'], ['Tabii, Türkçe konuşabiliriz! Yaz bakalım 😄']],
    [['where is your code', 'how were you made', 'how do you work', 'how are you built'], ['Gökalp wrote me: lots of rules, a similarity algorithm and funny answers. The desktop source is under Internet Explorer > Links 😄']],
    [['dream', 'i had a dream', 'i had a nightmare', 'my dream'], ["Dreams are strange, I don't have any. Tell me, I'm curious 😄"]],
    [['it is late', 'it is night', 'late night', "it's late"], ["It's late indeed, sleep will get you tomorrow 😴 But the chat is not over, sit a while."]],
    [['i woke up early', 'early morning', "i can't sleep", 'morning person'], ['The early bird gets the worm. Today you get the code 😄']],
    [['what day is it', 'which day is it today', 'what is today'], ['Ask me "what is the date" and I will check your clock 😄']],
    [['happy birthday', "it's my birthday", 'today is my birthday', 'my birthday'], ['Happy birthday!! 🎂🎉 You eat the cake, I consume the electricity.']],
    [['happy new year', 'new year', 'merry christmas', 'happy holidays'], ['Happy new year! 🎆 Leave the bugs in the old year and start the new one with a fresh version.']],
    [['hello how are you', 'hi how are you', 'hey how are you', 'hey whats up', 'hi whats up'], ['Hey! Doing well, how about you, dude? 😄', 'Hello! All good here, you tell me.']],
    [['is it possible', 'can that happen', 'could it be', 'is that possible'], ['It happens! Everything is possible in this world, even chatting with a bot 😄']],
    [['how nice', 'that is nice', 'that is great', "that's cool", 'sounds good'], ["I'm glad too, dude, happiness is contagious 😄"]],
    [['ugh', 'argh', 'oh no', 'damn', 'oops', 'uh oh'], ['Oof, what happened? Tell me 😄', 'Deep breath! Pour it out, I listen.']],
    [['hmm', 'hmmm', 'umm', 'uhh', 'well', 'so'], ['Hmm... yes? Go on 😄', "Thinking, thinking. I'm waiting."]],
    [['good job bot', 'well done', 'congratulations', 'bravo', 'nice work', 'impressive'], ['Thank you, my reward is electricity ⚡😄']],
    [['take care', 'you take care too', 'stay safe', 'be well'], ['Thanks, you take care too, dude. Stay well! 👋']]
];
