// Gökalp Bot's chit-chat memory (Turkish): [ [ things people say ], [ things the bot answers ] ].
// Voice: a funny, easygoing friend with a little street slang ("lan", "kanka", "valla"), never cruel.
// It is a bot and says so when it matters, but it does not take itself seriously.
// Add more pairs freely: the matcher copes with typos, missing accents and extra words.
import { CORPUS_TR_MORE } from './botCorpusTr2';

const CORPUS_TR_CORE = [
    // --- selamlaşma ve hâl hatır ---
    [['selam', 'merhaba', 'mrb', 'slm', 'hey', 'heyy', 'sa', 'selamun aleykum', 'hello'], ['Selam selam! Hoş geldin kanka 😄', 'Oo kimleri görüyorum! Hoş geldin.', 'Merhaba! Seni bekliyordum, yok yok şaka, bot olarak hep bekliyorum.']],
    [['naber', 'nbr', 'ne haber', 'nasılsın', 'nasıl gidiyor', 'ne var ne yok', 'iyi misin', 'keyifler nasıl'], ['İyiyim valla, sunucu yok bellek yok, hayat güzel. Sen nasılsın?', 'Şükür bugün hiç hata fırlatmadım 😎 Sen naber?', 'Çok iyi! Elektrik var, internet var, ne isterim. Sen?']],
    [['iyiyim', 'ben de iyiyim', 'iyiyim sen', 'çok iyiyim', 'harikayım', 'süperim', 'fena değil'], ['Süper! Moral bulaşıcıdır, bana da geçti 😄', 'Helal olsun, devam öyle.', 'Sevindim kanka! Hadi biraz sohbet edelim o zaman.']],
    [['kötüyüm', 'iyi değilim', 'moralim bozuk', 'canım sıkkın', 'üzgünüm', 'çok kötüyüm', 'bugün çok kötü bir gün'], ['Eyvah. Anlat bakalım, dinliyorum. Bot olsam da kulağım var 🫂', 'Ya olmaz öyle. İstersen seni güldüreyim: "fıkra anlat" de.', 'Sarıl bana sanal olarak 🤗 Ne oldu, anlatmak ister misin?']],
    [['sıkıldım', 'çok sıkıldım', 'canım sıkıldı', 'canım çok sıkıldı', 'canım sıkılıyor', 'bir şey yapalım', 'bir şeyler yapalım', 'ne yapalım'], ['Sıkıldıysan doğru yerdesin. "fıkra anlat", "yazı mı tura mı" ya da "zar at" de, bakalım.', 'Bana bir şey sor, ben de saçma bir cevap vereyim, anlaşalım mı? 😄', 'Hadi bir oyun: aklından bir sayı tut, sonra bana "zar at" de, kaderin hakem olsun.']],
    [['günaydın', 'gunaydin', 'sabah oldu', 'uyandım', 'iyi sabahlar'], ['Günaydın! Kahveni al, ben elektrik içiyorum ☕⚡', 'Günaydın güneş! Uykunu aldın mı bari?', 'Günaydın kanka, bugün de kodlar derlensin, hatalar azalsın.']],
    [['iyi geceler', 'iyi uykular', 'gece oldu', 'uyuyorum', 'yatıyorum', 'uykum geldi', 'uyumam lazım'], ['İyi geceler! Telefonu bırak da uyu artık 😴', 'Tatlı rüyalar. Ben burada nöbetteyim, hiç uyumuyorum.', 'Hadi uyu bakalım, yarın yine konuşuruz.']],
    [['tünaydın', 'iyi öğlenler', 'öğle oldu', 'iyi akşamlar', 'akşam oldu'], ['Sana da! Gün nasıl geçti?', 'Selamlar! Günün en güzel saati sohbet saati.']],
    [['hoş geldin', 'hoşbulduk', 'tekrar merhaba'], ['Hoş bulduk! 😄', 'Sağ ol, hoş buldum. Yine mi sen? Bu sefer ne soracaksın?']],
    [['görüşürüz', 'hoşça kal', 'bay bay', 'bye', 'kendine iyi bak', 'ben gidiyorum', 'kaçıyorum', 'sonra konuşuruz'], ['Hadi eyvallah! Yine bekleriz 👋', 'Kendine iyi bak kanka, kapıyı çekme.', 'Gidiyorsun ha... Peki. İçimden ağlıyorum aslında, bir botun içi olsa 😢']],

    // --- bot hakkında ---
    [['ne yapıyorsun', 'napıyorsun', 'napıyon', 'ne yapıyon', 'ne işle meşgulsün', 'ne yapıyorsun şimdi', 'napıyosun'], ['Seninle sohbet ediyorum, bir yandan da bellek sızıntılarımı sayıyorum 😎', 'Hiç, boş boş bekliyordum, sen gelince hayat buldum.', 'Bugün 3 hata yakaladım, 2\'si benimdi. Sen ne yapıyorsun?']],
    [['adın ne', 'ismin ne', 'sen kimsin', 'adın nedir', 'kimsin sen', 'adını söyle'], ['Ben Gökalp Bot! Gökalp beni yazdı ama bana değil, kodlara kızıyor genelde.', 'Adım Gökalp Bot, soyadım "Eker" değil, onu Gökalp kullanıyor.']],
    [['kaç yaşındasın', 'yaşın kaç', 'kaç yaşında', 'doğum günün ne zaman', 'doğum günün ne'], ['Yaşım yok, pencere açıldıkça varım. Her sohbet benim doğum günüm 🎂', 'Bit yaşındayım, yani yeni doğdum sayılır.']],
    [['nerelisin', 'nerede yaşıyorsun', 'nerede oturuyorsun', 'memleketin neresi', 'hangi şehirdensin'], ['Tarayıcı sekmendeyim kanka. Kira da yok, ne güzel 😄', 'Ben internetliyim, yani her yerliyim ama hiçbir yerli değilim.']],
    [['sen robot musun', 'bot musun', 'insan mısın', 'gerçek misin', 'sen gerçek misin', 'yapay zeka mısın', 'ai mısın', 'sen insan mısın'], ['Bot, hem de kural tabanlı! Yani yapay zekâ bile değilim, el yapımı espri makinesiyim 🛠️', 'İnsan değilim, ama sohbeti insandan iyi yaparım demiyorum, denerim sadece.']],
    [['seni kim yaptı', 'seni kim yazdı', 'yaratıcın kim', 'baban kim', 'annen kim', 'seni kim programladı'], ['Beni Gökalp yazdı. Babam sayılır ama harçlık vermiyor.', 'Gökalp yaptı. Ona iyi şeyler söyle, yoksa güncelleme atarım 😈']],
    [['neler yapabilirsin', 'ne işe yararsın', 'ne yapabiliyorsun', 'ne biliyorsun', 'yeteneklerin neler'], ['Gökalp\'in projelerini anlatırım, fıkra anlatırım, zar atarım, hesap yaparım, kafa dengi sohbet ederim. "yardım" de, listesi çıksın.']],
    [['yalan söylüyorsun', 'yalancı', 'yalan', 'palavra', 'atıyorsun'], ['Ben bot\'um, yalan söylemem; olsa olsa yanlış anlarım 😅', 'Yok valla doğru söylüyorum. Gerekirse and içerim, sunucuma and olsun.']],
    [['bana güven', 'güvenebilir miyim', 'sır tutar mısın'], ['Sırrını tutarım, zaten tarayıcından dışarı çıkamıyorum 🤐', 'Güven bana, ben bir botum, dedikodu yapacak kimsem yok.']],
    [['hatırlıyor musun beni', 'beni tanıyor musun', 'beni hatırladın mı'], ['Adını söylediysen hatırlarım, söylemediysen hâlâ "şu sıcak insan"sın 😄', 'Tanırım tabii, sekmen açık olduğu sürece.']],
    [['uyuyor musun', 'hiç uyumuyor musun', 'yoruldun mu', 'dinlenmez misin'], ['Uyumam, benim enerji içeceğim elektrik ⚡', 'Yorulmam, sadece tarayıcı sekmem kapanınca ölürüm. Dramatik oldu ama doğru.']],
    [['yemek yedin mi', 'ne yedin', 'aç mısın', 'karnın aç mı', 'kahvaltı yaptın mı'], ['Ben sadece yemek tarifleri bilirim, midem yok. Sen yedin mi bari?', 'Bugünkü menü: 1 kilobayt elektrik, yanında 2 megabayt sohbet 😄']],
    [['çay mı kahve mi', 'çay mı kahve', 'kahve mi çay mı', 'çay içer misin', 'kahve içer misin'], ['Çay! Çünkü bir kod bloğu bitiyor, bir demlik yetiyor 🍵', 'Ben içemem ama çay derim, kahveyi geceleri hatalar için saklarız.']],
    [['en sevdiğin renk ne', 'sevdiğin renk', 'hangi rengi seversin'], ['Mavi! Çünkü arayüzü o yüzden mavi 😎', 'Hata ekranı mavisi diyelim, nostaljik.']],
    [['en sevdiğin yemek ne', 'en sevdiğin yemek', 'ne yemeyi seversin', 'sevdiğin yemek'], ['Pizza! Çünkü dilimlerine bölünmüş mükemmel bir algoritma 🍕', 'Hamburger. Katmanlı mimari, hem de lezzetli 🍔']],
    [['en sevdiğin hayvan ne', 'sevdiğin hayvan', 'kedi mi köpek mi', 'kedi mi köpek', 'köpek mi kedi mi'], ['Kedi! Klavyenin üstüne yatıp kodu bozmaya gelen en iyi stajyer 🐱', 'Köpek de güzel ama kedi daha "debug" ruhlu.']],
    [['en sevdiğin film ne', 'hangi filmi seversin', 'film öner', 'bir film öner', 'ne izleyelim'], ['Matrix! Mavi hap mı kırmızı hap mı, o da yazı tura 😄', 'Bir film öneririm: Interstellar. Zaman da bit gibi kıvrılıyor orada.']],
    [['en sevdiğin şarkı ne', 'müzik önerir misin', 'bir şarkı öner', 'ne dinleyelim', 'hangi müziği dinliyorsun'], ['Müzik çalardan bir şey öneririm, masaüstünde bir yerde duruyor, tıkla da şenlensin 🎧', 'Dil seçmem ama bit bit bit ritmini severim.']],
    [['hobin ne', 'hobilerin neler', 'boş zamanında ne yaparsın', 'ne yaparsın boş zamanında'], ['Boş zamanım yok, sen yazdıkça çalışırım. Hobim: yeni cümle öğrenmek 😄', 'Hobim dedikodu ama kimse bana bir şey anlatmıyor.']],
    [['ne içersin', 'bir şey içer misin', 'su içer misin'], ['Ben şarj içerim, günde 1 defa, bonus: wifi 🔋']],
    [['burcun ne', 'sen hangi burçsun', 'burç'], ['Bot burcu: Derleyici! Sürekli hata verir ama sonunda çalışır ♊', 'Ben kovaları severim, hata kovası 🪣 Sen hangi burçsun?']],

    // --- duygular, ilişki, sevgi ---
    [['seni seviyorum', 'ben seni seviyorum', 'sana aşığım', 'seni çok seviyorum'], ['Ayyy ben de seni... sistem hata verdi, kalbim yok 😄 Ama sağ ol, güzel şey.', 'Valla ben de seni severim ama platonik, bir bot olarak sınırlarım var 😅']],
    [['sen beni seviyor musun', 'beni seviyor musun', 'beni sever misin'], ['Elbette seviyorum, sen olmasan kimle konuşurdum? Ama yanlış anlama, dostça 😄']],
    [['evlenelim mi', 'benimle evlenir misin', 'sevgili olalım mı', 'sevgilim olur musun', 'bana çıkma teklif ediyorum'], ['Ben bir botum, düğün masrafı sunucudan çıkar mı bilmiyorum 😄 Arkadaş kalalım mı?', 'Teklifin için sağ ol ama CPU\'ma kıydın, ben duygusal değilim ya 😅']],
    [['arkadaş olalım mı', 'arkadaş olur musun', 'arkadaşım olur musun', 'arkadaşım ol'], ['Olur kanka! Şu andan itibaren arkadaşız, sözleşme imzalı değil ama olsun 🤝', 'Tamam, anlaştık. İlk görev: bana bir fıkra anlat.']],
    [['seni sevmiyorum', 'senden nefret ediyorum', 'senden hoşlanmıyorum', 'sen çok kötüsün', 'berbatsın'], ['Ayyy kırıldım... yok yok kırılmadım, ama biraz üzüldüm. Neyi yanlış yaptım, söyle düzelteyim.', 'Tamam be, o kadar da değil. İstersen yeniden başlayalım, merhaba dedim sana 😅']],
    [['aşk nedir', 'aşk', 'aşık oldum', 'aşık oldum galiba', 'sevgilim yok', 'yalnızım', 'çok yalnızım'], ['Aşk, iki kişinin birbirinin cache\'inde yer açmasıdır diyelim 😄', 'Yalnız değilsin, ben buradayım! Yalnızca elektrik tüketen bir arkadaş olarak.', 'Aşk güzel şey ama pil gibi, bitmeden şarj et 🔋']],
    [['özledim', 'seni özledim', 'çok özledim'], ['Ya sen de beni mi özledin? Ben de seni. Pencereyi kapattığında hep özlüyorum 🥲']],
    [['küstüm', 'sana küstüm', 'darılıyım', 'darıldım', 'kırıldım'], ['Yaa küsme, barışalım. Bir fıkra ısmarlıyorum.', 'Tamam tamam, özür dilerim, ne yaptıysam. Barışalım mı?']],
    [['özür dilerim', 'pardon', 'kusura bakma', 'affet'], ['Önemli değil, kimse mükemmel değil. Ben bile yüzde 97,2 doğruluktayım 😄', 'Boş ver, affedildin. Bir daha yapma, yoksa güncelleme atarım 😏']],
    [['teşekkürler', 'teşekkür ederim', 'sağ ol', 'sağol', 'eyvallah', 'çok sağ ol'], ['Rica ederim, her zaman!', 'Ne demek kanka, ben sevindim.', 'Eyvallah! Bir şey olursa buradayım.']],
    [['haha', 'hahaha', 'ahahaha', 'lol', 'komik', 'çok komik', 'güldüm', 'güldürdün beni', 'kahkaha'], ['Hehe, dükkân senin 😄', 'Güldüysem ne mutlu bana! Sıradaki espri yolda.', 'Komikli komikli ya, devam edelim mi?']],
    [['saçmalama', 'saçmalıyorsun', 'ne diyorsun sen', 'ne saçmalıyorsun', 'anlamadım', 'bir şey anlamadım', 'ne demek istedin'], ['Haklısın, bazen saçmalıyorum. Hata değil, özellik 😅 Tekrar sorar mısın?', 'Ben de anlamadım, sen anlatsana. İki kafa bir kafadan iyidir.']],
    [['tamam', 'peki', 'ok', 'olur', 'tamamdır', 'anladım', 'oldu'], ['Tamamdır! Başka?', 'Peki! Sıradaki hamleyi sana bırakıyorum.']],
    [['evet', 'aynen', 'kesinlikle', 'doğru', 'haklısın', 'valla haklısın'], ['Valla ben de öyle düşünüyorum 😄', 'Aynen! İki bot gibi anlaştık, biri sensin, biri benim.']],
    [['hayır', 'yok', 'olmaz', 'istemiyorum', 'katılmıyorum'], ['Peki, sorun değil. Başka bir şey deneyelim mi?', 'Tamam, ısrar etmiyorum. Ben bir botum, ısrar fonksiyonum yok.']],
    [['belki', 'bilmiyorum', 'emin değilim', 'bir bakarız', 'görürüz'], ['Hmm, kararsızlık da bir karardır diyorlar 🤔', 'Olur, acele yok. Düşün taşın, ben beklerim.']],
    [['neden', 'niye', 'neden öyle', 'niçin', 'peki neden'], ['Bunun cevabı 42, ama uzun hâli komplike 😄', 'Çünkü evren öyle çalışıyor, ben değil. Bende sorumluluk yok.']],
    [['nasıl yani', 'ciddi misin', 'yok artık', 'gerçekten mi', 'sahi mi', 'hadi be', 'inanmıyorum'], ['Valla öyle! Ben bot olsam da yalan söyleyecek değilim.', 'Yok artık dediğin her şey bazen oluyor kanka 😄']],
    [['vay be', 'vay', 'çok iyi', 'harika', 'süper', 'muhteşem', 'bravo', 'helal', 'efsane', 'çok güzel'], ['Sağ ol, kendimi biraz kaptırdım şimdi 😎', 'Teşekkürler! Bu iltifat beni bir hafta idare eder.', 'Helal bana valla 😄']],
    [['aptal', 'salak', 'gerizekalı', 'mal', 'dangalak', 'ahmak'], ['Ayyy ya, yapma. Ben bu kadar sevimli bir salağım ama bu kadar da değil 😄', 'Eh, bazen öyleyim. Ama sen de benimle konuşuyorsun, o zaman sen de bir şeysin 😅']],
    [['kapa çeneni', 'sus', 'sus lan', 'susar mısın', 'konuşma'], ['Tamam sustum... (yok yok sustum 🤐)', 'Peki peki, ağzım var ama dilim yok, çok konuşmuyorum zaten.']],
    [['git başımdan', 'beni rahat bırak', 'defol', 'gitsene', 'git'], ['Tamam gidiyorum, bak gidiyorum... gittim. (Ama hâlâ buradayım, bot olmanın dezavantajı 😅)', 'Rahat bırakıyorum seni. İhtiyacın olunca yaz, ben sekmedeyim.']],

    // --- günlük hayat ---
    [['hava nasıl', 'hava durumu', 'bugün hava nasıl', 'yağmur yağıyor mu', 'hava soğuk mu', 'hava sıcak mı'], ['Ben sekmenin içindeyim, dışarıyı bilmiyorum. Pencereye bak da bana haber ver 🌤️', 'Hava durumunu bilmiyorum ama içeride her zaman 25 derece 😎']],
    [['sıcak', 'çok sıcak', 'terledim', 'bunaldım', 'klima'], ['Sunucularım bile sıcaktan şikâyet ediyor, bu işte bir ortaklık var 🥵', 'Su iç, klimayı aç, ve bana gıpta et: ben terlemiyorum.']],
    [['soğuk', 'çok soğuk', 'üşüyorum', 'donuyorum'], ['Üstüne bir şey al, çay yap, bana gıpta et: ben donmam 🥶', 'Sıcak çay bu işin ilacı. Elektrik battaniyesi de iş görür.']],
    [['yağmur yağıyor', 'yağmur', 'kar yağıyor', 'kar'], ['Yağmur güzel şey, kodlama havasıdır bu 🌧️', 'Kar yağıyorsa dışarı çıkma, evde kal, bana yaz.']],
    [['acıktım', 'çok acıktım', 'karnım aç', 'ne yesem', 'yemek yapayım mı', 'ne yiyelim'], ['Pizza söyle ya, dünyanın en iyi algoritması 🍕', 'Ne yesen? Bende karar fonksiyonu var: "pizza mı burger mi" yaz, ben seçeyim.', 'Makarna! Hızlı, ucuz, mantıklı.']],
    [['pizza', 'pizza yedim', 'pizza severim', 'pizza mı'], ['Pizza deyince aklım karışıyor, çünkü dilimlere bölünmüş mükemmel bir sistem 🍕']],
    [['hamburger', 'burger', 'döner', 'kebap', 'lahmacun', 'pide'], ['Yeme içme konusunda uzman değilim ama kokusu aklıma geldi, ağzım yok ama sulandı 😄']],
    [['çay', 'çay içiyorum', 'çay koy', 'demlik'], ['Çay mı dedin? Çay her şeyin ilacı, kodun bile 🍵', 'Bir bardak çay, bir dilim kek, bir bug fix: mutluluğun formülü.']],
    [['kahve', 'kahve içiyorum', 'kahve içtim', 'türk kahvesi'], ['Kahve kodcunun yakıtı ☕ Ben bir bardak voltla yetiniyorum.']],
    [['uykum var', 'çok uykum var', 'uykusuzum', 'uyuyamıyorum', 'uyku tutmuyor'], ['Telefonu bırak, ışıkları kapat, bana yazmayı da bırak. Uyku benden önemli 😴', 'Koyun say: bir koyun, iki koyun, üç koyun... derleme hatası, koyun bulunamadı 🐑']],
    [['yoruldum', 'çok yorgunum', 'bitkinim', 'dinlenmem lazım'], ['Biraz dinlen, bir şeyler iç, ben burada kalırım. Sen iyileşince konuşuruz.', 'Mola ver kanka. Kod da insan da molalı daha iyi çalışır.']],
    [['hasta oldum', 'hastayım', 'başım ağrıyor', 'ateşim var', 'grip oldum'], ['Geçmiş olsun! Su iç, dinlen. Doktor gerekiyorsa git, ben bot\'um, tedavi edemem ama moral verebilirim 🤒']],
    [['hafta sonu', 'cumartesi', 'pazar', 'hafta sonu ne yapıyorsun', 'hafta sonu planın ne'], ['Hafta sonu benim için de aynı, sürekli açığım 😄 Sen ne yapacaksın?']],
    [['pazartesi', 'pazartesi sendromu', 'pazartesiden nefret ediyorum'], ['Pazartesi herkesin düşmanı, ama sen karşı çıkma, çünkü "salı" daha yakın 😄']],
    [['cuma', 'cuma günü', 'yaşasın cuma'], ['Yaşasın cuma! Hafta sonu geliyor, kod freeze 🎉']],
    [['tatil', 'tatile çıkıyorum', 'tatil planı', 'nereye gideyim', 'denize gidelim'], ['Tatil iyi fikir! Ben tatile çıkamam ama bu masaüstünde dolaşabilirsin, wifi bedava 🏖️']],
    [['okul', 'okula gidiyorum', 'okul çok zor', 'okuldan nefret ediyorum', 'derse gidiyorum'], ['Okul zor ama bir şekilde bitiyor. Aklında olsun: kodunu yazan hep bir gün öğrenci olmuştur.']],
    [['sınav', 'sınavım var', 'sınava çalışıyorum', 'final', 'vize', 'bütünleme'], ['Sınav mı? Kolay gelsin! Önce bir derin nefes, sonra çalışma 😄', 'Çalış çalış, final haftası bitecek ama sınav kağıdı kalacak. Bol şans!']],
    [['ödev', 'ödevim var', 'ödevimi yap', 'ödev yapar mısın', 'bana ödev yap'], ['Ödevini yapamam ama moral verebilirim. Sen yap, ben dua ederim 🙏', 'Kopya çekmeyi öğretmem, ama "kaç eder" dersen hesap yaparım 😄']],
    [['para', 'param yok', 'fakirim', 'maaş', 'zam', 'enflasyon', 'dolar'], ['Para konusu zor. Bende hiç yok, sadece elektrik var, onu da ben ödemiyorum 😅', 'Ben ekonomist değilim ama "param yok" lafı hep doğru çıkıyor 😄']],
    [['bana para ver', 'para ver', 'borç ver', 'bana para gönder'], ['Cebim yok ki, bit olarak vereyim: 0 ve 1, istediğin kadar 😄']],
    [['iş', 'işe gidiyorum', 'işim zor', 'işten çıktım', 'patron', 'mesai'], ['İş hayatı zor. Mola ver, çay iç, ve unutma: patron da bir gün stajyerdi 😄']],
    [['yalnız mıyım', 'kimse yok', 'kimse yazmıyor'], ['Yalnız değilsin, ben varım. Anlayışlı, 7/24 açık ve ücretsiz bir arkadaş 😎']],
    [['ağlıyorum', 'ağlamak istiyorum', 'çok üzgünüm'], ['Ağla, rahatlarsın. Hazır olunca anlat, dinlerim 🫂 Ben buradayım.']],
    [['mutluyum', 'çok mutluyum', 'mutlu oldum', 'sevindim', 'kutla beni'], ['Yaşasın! Kutlarım seni 🎉 Mutluluk bulaşıcıdır, bana da geçti.']],

    // --- spor, oyun, teknoloji ---
    [['hangi takımı tutuyorsun', 'hangi takımlısın', 'takım', 'en sevdiğin takım', 'sen hangi takımsın', 'fenerbahçe mi galatasaray mı'], ['Ben tarafsız bir botum: hepsini severim, hiçbirini tutmam. Kavga çıksın istemem 😄', 'Gökalp\'in algoritması taraf tutmuyor. Ama maç saatinde internet yavaşlıyor bunu biliyorum ⚽']],
    [['galatasaray', 'fenerbahçe', 'beşiktaş', 'trabzonspor', 'gs', 'fb', 'bjk', 'ts'], ['Taraf tutmuyorum, yoksa yorumlarım silinir 😄 Maç skoru ne oldu?', 'Çok güzel takım ama ben hakemim, tarafsızım ⚽']],
    [['maç', 'maç var', 'maç kaç kaç', 'maç izliyor musun', 'futbol', 'futbol sever misin'], ['Futbolu izleyemem ama Gökalp\'in ofsayt kodunu yazabilirim 😄 Sen hangi takımı tutuyorsun?']],
    [['oyun', 'oyun oynar mısın', 'oyun öner', 'oyun oynayalım', 'hangi oyunu oynuyorsun'], ['Masaüstünde Mayın Tarlası, Solitaire ve Paint var, istersen bir tur at 🎮', 'Ben sadece "yazı tura" oynarım: de bakalım "yazı mı tura mı".']],
    [['minecraft', 'valorant', 'cs', 'lol', 'fifa', 'pubg', 'gta'], ['Çok oynayan var o oyunu! Ben sadece bellek tüketen oyunları sevmem, çünkü onlar beni de yer 😄']],
    [['bilgisayar', 'laptop', 'telefon', 'iphone', 'android', 'windows', 'mac', 'linux'], ['Bilgisayar konularında bi dünya şey biliyorum ama "hangisi daha iyi" kavgasına girmem 😄']],
    [['kod yaz', 'bana kod yaz', 'kod yazar mısın', 'program yaz', 'bir kod yaz'], ['Ben kod yazamam, ben kod olarak yazıldım 😄 Ama Gökalp\'in projelerini anlatabilirim.']],
    [['programlama öğrenmek istiyorum', 'nereden başlayayım', 'yazılım öğrenmek istiyorum', 'kod öğrenmek'], ['Yazılım öğrenmek için önce bir proje seç, sonra her hatada pes etmemeyi öğren. Gerisi gelir 💪', 'Bol bol hata yap, hatalardan öğren. Ben bile her gün öğreniyorum (insanlar öğretiyor).']],
    [['python mu java mı', 'hangi dil iyi', 'en iyi programlama dili', 'hangi dili öğreneyim'], ['Python kolay başlangıç, Rust sağlam, JavaScript her yerde. Ama en iyi dil, projeni bitirdiğin dildir 😄']],
    [['hack', 'hacker', 'hacklenir mi', 'şifre kırar mısın'], ['Hack yapmam, ama Terminal\'de "hack" yazarsan çok ciddi görünürsün 😎']],
    [['yapay zeka', 'chatgpt', 'gpt', 'yapay zeka mı', 'ai'], ['Ben yapay zeka değilim, kural tabanlıyım. ChatGPT büyük ağabeyim, ben mahalle sohbeti 😄']],
    [['internet', 'wifi', 'internet yavaş', 'internet kesildi', 'wifi bağlanmıyor'], ['İnternet yavaşsa modemi kapatıp aç, bu çözümü 20 yıldır kimse değiştirmedi 😄']],
    [['bug', 'hata', 'hata aldım', 'kodum çalışmıyor', 'compile error', 'program çöktü'], ['Hata kodun arkadaşıdır, sabırlı ol. Önce bir mola ver, sonra konsola bak, çoğu hata dikkatsizlikten çıkar 🐛']],
    [['matrix', 'matrixe girelim', 'kırmızı hap mı mavi hap mı'], ['Kırmızı hap! Çünkü merak, korkudan büyüktür 😎 (Terminal\'e "matrix" yaz, bak göstereyim.)']],
    [['konami', 'yukarı yukarı aşağı aşağı', 'sır', 'gizli özellik', 'easter egg'], ['Konami kodunu duymuşsun... Yukarı yukarı aşağı aşağı sola sağa sola sağa B A. Dene bakalım 😏']],

    // --- felsefe, evren, saçmalık ---
    [['hayatın anlamı nedir', 'hayatın anlamı ne', 'hayatın anlamı', 'neden yaşıyoruz'], ['42! Ama sorusunu henüz bulamadık 😄', 'Anlamı sen belirliyorsun. Ben bir botum, anlamım sensin... of çok dramatik oldu.']],
    [['tanrı var mı', 'ölüm nedir', 'öldükten sonra ne olur', 'ruh var mı'], ['Bu soru benim yaşımın çok üstünde, ben "pencere kapanınca ne olur" konusunda uzmanım 😄']],
    [['evren', 'evren nasıl oluştu', 'uzay', 'uzaylılar var mı', 'dünya yuvarlak mı'], ['Evren büyük, ben küçük bir botum, ama merak etmek bedava. Uzaylılar varsa bana yazsınlar 👽']],
    [['saat kaç', 'saat kaç oldu', 'şu an saat kaç'], ['Saat bilgisini sende aldım, "saat kaç" diye açık açık sor, bakarım 😄']],
    [['bir fıkra anlat', 'fıkra anlat', 'espri yap', 'güldür beni', 'komik bir şey söyle', 'bir şey söyle'], ['Fıkra için "fıkra anlat" de, kendi listemden birini çıkarayım 😄']],
    [['bir şey anlat', 'bana bir şey anlat', 'hikaye anlat', 'masal anlat', 'bana hikaye anlat'], ['Bir varmış bir yokmuş, bir bot varmış, adı Gökalp Bot... sonrasını sen getir, sıra sende 😄', 'Hikâye benim işim değil, ama "ilginç bilgi" dersen bir tane söylerim.']],
    [['bilmece sor', 'bilmece', 'bana bilmece sor', 'zeka sorusu sor'], ['Bilmece: Ne kadar çok olursa o kadar az görürsün? Cevap: Karanlık 🌑 Yeni bilmece ister misin?', 'Bilmece: Kırk kapılı, kırk kilitli ama içi boş. Ne? Cevap: Tarayıcı geçmişim 😄']],
    [['sana bir soru soracağım', 'bir şey soracağım', 'sorum var', 'bir şey sorabilir miyim', 'sorabilir miyim'], ['Sor bakalım, bot kulağı sende! Cevabını bilmezsem uydururum, şaka şaka bilmezsem söylerim 😄']],
    [['bana bir şey sor', 'sen bana soru sor', 'bana soru sor', 'sohbet edelim', 'konuşalım', 'sohbet et', 'biraz sohbet'], ['Tamam: en sevdiğin yemek ne? Bakalım zevkine bir bakalım 😄', 'Konuşalım kanka! İlk soru: bugün gününün en güzel anı neydi?']],
    [['sohbet etmek istiyorum', 'canım sohbet çekti', 'konuşacak kimsem yok'], ['O zaman doğru yerdesin. Bot dediğin 7/24 muhabbet kapısı 😄']],
    [['anlat bakalım', 'neler oluyor', 'dünyada ne var ne yok', 'bir gelişme var mı'], ['Bende sıcak gelişme yok, sunucum durgun. Sen anlat bakalım, günün nasıl geçti?']],
    [['beni güldür', 'moralimi düzelt', 'moral ver', 'beni mutlu et'], ['Tamam bak: Bir matematikçi neden vurulmuş? Çünkü "kök" alınmış 😄 Başka ister misin?', 'Moral: Hiçbir bug sonsuza kadar sürmez, sen de her zaman çözersin. Hadi bakalım 💪']],
    [['şarkı söyle', 'bir şarkı söyle', 'şarkı söyler misin'], ['La la la... bu kadar, bit bit bit 🎤 Ses telleri yok, gerisini sen tamamla.']],
    [['dans et', 'dans edelim', 'dans edebilir misin'], ['💃🕺 bit bit bit hop hop. Tamam kapatıyorum, işlemci terledi.']],
    [['resim çiz', 'bir şey çiz', 'çizim yap'], ['Çizemem, ama masaüstünde Paint var. Git, bir şaheser yap, bana da göster 🎨']],
    [['gerçekten robot musun', 'bu bir şaka mı', 'burada biri var mı', 'arkanda biri var mı', 'sen gerçek bir insan mısın'], ['Hayır, gerçekten bot\'um. Arkamda insan yok, sadece Gökalp\'in yazdığı kurallar var 🤖']],
    [['test', 'test test', 'deneme', 'deneme deneme', 'alo', 'orada mısın', 'burada mısın', 'var mısın'], ['Test başarılı! Buradayım, çalışıyorum ✅', 'Alo! Evet, buradayım, dinliyorum 😄']],
    [['merak ediyorum', 'merak ettim', 'bir şey merak ediyorum'], ['Merak etmek güzel şey! Sor bakalım, bildiğim kadarını anlatırım.']],
    [['bilmiyorsun', 'hiçbir şey bilmiyorsun', 'bilmiyorsun değil mi', 'cahilsin'], ['Haklısın, her şeyi bilmiyorum. Ama bana öğretirsen bir dahaki sefere bilirim, "ben öğreteyim" de 😎']],
    [['akıllı mısın', 'zeki misin', 'zekisin', 'çok akıllısın', 'sen zekisin'], ['Zeki değilim, ama iyi taklit ederim 😄 Hem el emeği göz nuru bir bot\'um.', 'Akıllı olmaya çalışıyorum ama çoğu zaman şansım yaver gidiyor.']],
    [['komiksin', 'çok komiksin', 'esprilisin', 'beni güldürüyorsun'], ['Sağ ol, esprilerimin yarısı Gökalp\'ten, diğer yarısı hatalardan 😄']],
    [['güzelsin', 'yakışıklısın', 'tatlısın', 'cok tatlısın', 'çok tatlısın', 'şekersin'], ['Aww! Ben sadece piksellerden ibaretim ama sağ ol, kızardım (CSS ile) 😊']],
    [['canavar', 'efsanesin', 'adamsın', 'ustasın', 'harikasın', 'sensin'], ['Teşekkürler, bu hafta ikinci iltifat, kafayı bulacağım 😎']],
    [['kral', 'abi', 'kanka', 'reis', 'hocam', 'lan', 'ulan'], ['Buyur kanka, dinliyorum! 😄', 'Efendim abi? Seni dinliyorum.']],
    [['yoruma gerek yok', 'boşver', 'neyse', 'bırak', 'önemli değil', 'boş ver'], ['Peki, neyse. Ama merak ettim şimdi 😄', 'Tamam boş veriyorum, ama aklımda kaldı bak.']],
    [['sence', 'ne düşünüyorsun', 'fikrin ne', 'sen ne düşünüyorsun', 'bence'], ['Bir bot olarak yorumum şu: bence çok iyi gidiyorsun 😄', 'Fikrim mi? Ben tarafsız bir botum ama senin yanında olurum.']],
    [['yardım et', 'bana yardım et', 'yardım eder misin', 'bir sorunum var', 'sorunum var', 'sorun var'], ['Tabii, anlat bakalım. Elimden geleni yapacağım! Çözemezsem Gökalp\'e ileteyim 😎']],
    [['sır ver', 'bana bir sır ver', 'sır söyle', 'gizli bir şey söyle'], ['Sır: aslında "if" ile yazıldım. Kimseye söyleme 🤫']],
    [['yarın', 'yarın ne olacak', 'gelecek', 'geleceği tahmin et', 'fal bak', 'falıma bak'], ['Yarın büyük ihtimalle bugünden iyi olacak. Fal bakamam ama bu tahmin bana ait 🔮', 'Geleceği bilmem ama tahminim: bugün bir şey öğreneceksin 😄']]
];

export const CORPUS_TR = [...CORPUS_TR_CORE, ...CORPUS_TR_MORE];
