// The Terminal's `fortune` command: short programmer wisdom, jokes and life advice, in both languages.
// Add more freely (keep each under about 150 characters so it fits the window).
export const FORTUNES = {
    en: [
        'It works on my machine.',
        'There are only two hard things in computer science: cache invalidation, naming things, and off-by-one errors.',
        'A good programmer looks both ways before crossing a one-way street.',
        'Weeks of coding can save you hours of planning.',
        'Real programmers count from zero.',
        "The cloud is just someone else's computer.",
        'Have you tried turning it off and on again?',
        'First, solve the problem. Then, write the code.',
        'Debugging is being the detective in a crime movie where you are also the murderer.',
        "Never trust a computer you can't throw out of a window.",
        'Today is a good day to commit.',
        'Ctrl+S is a lifestyle.',
        'A bug is just a feature that has not found its documentation yet.',
        'If at first you do not succeed, call it version 1.0.',
        'Good code is its own best documentation. Bad code is its own best excuse.',
        'The best code is the code you did not have to write.',
        'Code never lies, comments sometimes do.',
        'Weeks of debugging usually end with a missing semicolon.',
        'There is no place like 127.0.0.1.',
        'To understand recursion, you must first understand recursion.',
        'There are 10 kinds of people: those who understand binary and those who do not.',
        'Programming is 10% writing code and 90% understanding why it does not work.',
        'Measure twice, cut once, commit never (until it works).',
        'The only thing worse than no tests is tests you do not trust.',
        'Premature optimization is the root of a lot of weekends lost.',
        'A watched build never finishes.',
        'Deleting code is the most satisfying kind of coding.',
        'It is not a bug if you document it.',
        'If it is stupid but it works, it is still stupid. But it works.',
        'Fast, cheap, good: pick two. Bugs: you get all of them.',
        'Done is better than perfect, but a failing test is neither.',
        'Always code as if the person maintaining it is a violent psychopath who knows where you live. Or just be kind: it is usually you.',
        'The compiler is not your enemy, it is the friend that tells you the truth.',
        'Naming a variable "temp" is the first step to a long-term relationship with confusion.',
        'There is always one more bug.',
        'Friends do not let friends push on Friday afternoon.',
        'Your future self will thank you for writing it down.',
        'A rubber duck solves more bugs than a meeting does.',
        'Talk to the duck. The duck knows.',
        'Copy-paste is a design pattern. A questionable one.',
        'Stack Overflow is just a very large rubber duck.',
        'Keep calm and clear the cache.',
        'Be the semicolon you wish to see in the code.',
        'Every great program starts with a single "Hello, World".',
        'The best way to learn to code is to break things and fix them.',
        'Errors are not failures, they are free lessons.',
        'Read the error message. Then read it again. Slowly.',
        'When in doubt, add a log line.',
        'When in more doubt, add two.',
        'Take a walk. The bug will still be there, but you will see it.',
        'A short break fixes more bugs than a long night.',
        'If you can not explain it simply, you have not understood it yet.',
        'Simplicity is the ultimate sophistication, and the hardest feature to ship.',
        'Make it work, make it right, make it fast. In that order.',
        'Strong opinions, weakly held. Especially about tabs and spaces.',
        'Tabs versus spaces is the longest-running comedy in computing.',
        'Dark mode: because light attracts bugs.',
        'A programmer is a machine that turns coffee into code, and sometimes into bugs.',
        'Coffee first, merge conflicts later.',
        'Never debug while hungry.',
        'Sleep is the best debugger known to humankind.',
        'The most powerful line of code is the one you deleted.',
        'A clean desk is the sign of a messy repository.',
        'Git is a time machine that only works if you pressed commit.',
        'Commit early, commit often, and describe what you did, not what you hoped.',
        'Branches are cheap, regret is expensive.',
        'Always back up. The one time you do not, the disk will know.',
        'Passwords are like underwear: change them often and do not share them.',
        'Security is a process, not a feature.',
        'The weakest link in any system is usually a sticky note.',
        'Trust, but verify. Then verify the verification.',
        'Today is a great day to learn something new.',
        'You are exactly as good at this as the number of bugs you have fixed.',
        'Do not wait for inspiration. Start typing and it will show up.',
        'A small step every day beats a giant leap once a year.',
        'Progress, not perfection.',
        'The expert was once a beginner who did not quit.',
        'If you are stuck, you are about to learn something.',
        'Nobody writes perfect code. The good ones just fix it faster.',
        'Ask questions. Smart people do it all the time.',
        'Be kind to the beginners. You were one yesterday.',
        'A good teacher is a better debugger than a good manual.',
        'Learning to code is learning to think clearly. The rest is syntax.',
        'The best feature is the one that makes someone smile.',
        'Build something small that works before building something big that does not.',
        'The first 90% of the project takes 90% of the time. The last 10% takes the other 90%.',
        'It always takes longer than you expect, even when you take this law into account.',
        'Murphy was an optimist.',
        'Whatever can go wrong will, usually just after the demo starts.',
        'The demo always breaks. The only question is when.',
        'If everything seems to be going well, you have obviously overlooked something.',
        'A computer lets you make mistakes faster than any invention in history, except tequila and handguns.',
        'There is no such thing as a quick fix.',
        'Backups are for people who like happy endings.',
        'A user is someone who finds the bug you did not know existed.',
        'No code is as fast as the code that is never run.',
        'The internet: the only place where "just Google it" is both advice and an insult.',
        'Wi-Fi is the only thing that works better the closer you stand to the router.',
        'Always keep your passwords safe, and your coffee safer.',
        'Rome was not built in a day, but they were probably using a different framework.',
        'Programming is like cooking: taste often and never serve the first draft.',
        'Machines do what you tell them, not what you meant.',
        'Be curious. The best discoveries start with "huh, that is weird".',
        'If it ain\'t broke, do not touch it. If it is, do not touch it on Friday.',
        'Hope is not a deployment strategy.',
        'Every expert has bugs in their past. And present.',
        'Lines of code are not a measure of progress, unless you are measuring weight.',
        'The best interface is the one nobody notices.',
        'One day, all of this will be legacy code.',
        'Your code is a letter to a stranger. Make it readable.',
        'Be proud of the bugs you fixed, not only the features you shipped.',
        'Great things are built one boring commit at a time.',
        'Remember to drink water. You are not a server and you have no cooling system.',
        'Breathe. It is only a computer.',
        'May your builds be green and your coffee strong.',
        'May the source be with you.',
        'You will soon meet a stranger. They will ask you to fix their printer.',
        'A pleasant surprise awaits you: the bug was a typo.',
        'Good news: it compiles. Bad news: it compiles.'
    ],
    tr: [
        'Bende çalışıyor.',
        'Bilgisayar biliminde sadece iki zor şey var: önbellek geçersiz kılma, isim koymak ve bir eksik/fazla hataları.',
        'İyi bir programcı tek yönlü sokağı geçerken iki yana da bakar.',
        'Haftalarca kod yazmak, saatlerce plan yapmaktan seni kurtarabilir.',
        'Gerçek programcılar sıfırdan sayar.',
        'Bulut, başkasının bilgisayarından ibarettir.',
        'Kapatıp tekrar açmayı denedin mi?',
        'Önce problemi çöz. Sonra kodu yaz.',
        'Hata ayıklamak, katilin de sen olduğun bir polisiye filmde dedektif olmaktır.',
        'Pencereden fırlatamayacağın bir bilgisayara asla güvenme.',
        'Bugün commit atmak için güzel bir gün.',
        'Ctrl+S bir yaşam tarzıdır.',
        'Hata, belgesini henüz bulamamış bir özelliktir.',
        'İlk seferde başaramazsan adına 1.0 sürümü de.',
        'İyi kod kendi belgesidir. Kötü kod kendi bahanesidir.',
        'En iyi kod, yazmak zorunda kalmadığın koddur.',
        'Kod yalan söylemez, yorum satırları bazen söyler.',
        'Haftalarca süren hata ayıklama çoğu zaman eksik bir noktalı virgülle biter.',
        'Evim evim güzel evim: 127.0.0.1.',
        'Özyinelemeyi anlamak için önce özyinelemeyi anlaman gerekir.',
        '10 türlü insan vardır: ikili sistemi bilenler ve bilmeyenler.',
        'Programlamanın %10\'u kod yazmak, %90\'ı neden çalışmadığını anlamaktır.',
        'İki kere ölç, bir kere kes, çalışana kadar commit atma.',
        'Testsiz kodtan da kötüsü, güvenmediğin testlerdir.',
        'Erken optimizasyon, kaybolan hafta sonlarının kökenidir.',
        'Gözünün önünde derlenen proje asla bitmez.',
        'Kod silmek, kodlamanın en tatmin edici hâlidir.',
        'Belgelersen hata değil, özelliktir.',
        'Saçma ama çalışıyorsa hâlâ saçmadır. Ama çalışıyor.',
        'Hızlı, ucuz, iyi: ikisini seç. Hatalar: hepsi bedava.',
        'Bitmiş olan, mükemmel olandan iyidir ama başarısız bir test ikisi de değildir.',
        'Derleyici düşmanın değil, sana doğruyu söyleyen arkadaşındır.',
        'Değişkene "temp" adını vermek, kafa karışıklığıyla uzun bir ilişkinin ilk adımıdır.',
        'Her zaman bir hata daha vardır.',
        'Arkadaşlar arkadaşlarının cuma akşamı push yapmasına izin vermez.',
        'Gelecekteki sen, bunu not aldığın için sana teşekkür edecek.',
        'Lastik ördek bir toplantıdan daha çok hata çözer.',
        'Ördekle konuş. Ördek bilir.',
        'Kopyala-yapıştır bir tasarım desenidir. Tartışmalı bir tanesi.',
        'Stack Overflow, çok büyük bir lastik ördektir.',
        'Sakin ol ve önbelleği temizle.',
        'Kodda görmek istediğin noktalı virgül ol.',
        'Her büyük program tek bir "Merhaba Dünya" ile başlar.',
        'Kod yazmayı öğrenmenin en iyi yolu bir şeyleri bozup düzeltmektir.',
        'Hatalar başarısızlık değil, bedava derslerdir.',
        'Hata mesajını oku. Sonra yavaşça bir daha oku.',
        'Şüphe duyduğunda bir log satırı ekle.',
        'Daha çok şüphe duyduğunda iki tane ekle.',
        'Bir yürüyüşe çık. Hata orada olacak ama sen onu görürsün.',
        'Kısa bir mola, uzun bir geceden daha çok hata çözer.',
        'Basitçe anlatamıyorsan henüz anlamamışsındır.',
        'Basitlik en büyük zarafettir ve teslim edilmesi en zor özelliktir.',
        'Önce çalıştır, sonra doğrult, sonra hızlandır. Bu sırayla.',
        'Güçlü fikirler, gevşek bağlılık. Özellikle tab mı boşluk mu konusunda.',
        'Tab mı boşluk mu, bilişimin en uzun süren komedisidir.',
        'Karanlık mod: çünkü ışık böcekleri çeker.',
        'Programcı, kahveyi koda, bazen de hataya dönüştüren makinedir.',
        'Önce kahve, sonra birleştirme çakışmaları.',
        'Aç karnına hata ayıklanmaz.',
        'Uyku, insanlığın bildiği en iyi hata ayıklayıcıdır.',
        'En güçlü kod satırı, sildiğin satırdır.',
        'Temiz bir masa, dağınık bir depoya işarettir.',
        'Git, sadece commit attıysan çalışan bir zaman makinesidir.',
        'Erken ve sık commit at; umduğunu değil, yaptığını yaz.',
        'Dal açmak ucuzdur, pişmanlık pahalı.',
        'Hep yedek al. Almadığın tek gün disk bunu bilir.',
        'Şifreler iç çamaşırı gibidir: sık değiştir, kimseyle paylaşma.',
        'Güvenlik bir özellik değil, bir süreçtir.',
        'Her sistemin en zayıf halkası genelde bir yapışkan nottur.',
        'Güven ama doğrula. Sonra doğrulamayı da doğrula.',
        'Bugün yeni bir şey öğrenmek için harika bir gün.',
        'Bu işte, düzelttiğin hata sayısı kadar iyisin.',
        'İlham bekleme. Yazmaya başla, o gelir.',
        'Her gün atılan küçük adım, yılda bir atılan dev adımdan iyidir.',
        'Mükemmellik değil, ilerleme.',
        'Uzman, bir zamanlar bırakmayan bir acemiydi.',
        'Takıldıysan, yeni bir şey öğrenmek üzeresin demektir.',
        'Kimse kusursuz kod yazmaz. İyi olanlar daha hızlı düzeltir.',
        'Soru sor. Akıllı insanlar bunu sürekli yapar.',
        'Acemilere nazik ol. Sen de dün biriydin.',
        'İyi bir öğretmen, iyi bir kılavuzdan daha iyi hata ayıklar.',
        'Kod yazmayı öğrenmek net düşünmeyi öğrenmektir. Gerisi sözdizimidir.',
        'En iyi özellik, birini gülümseten özelliktir.',
        'Çalışmayan büyük bir şey yapmadan önce çalışan küçük bir şey yap.',
        'Projenin ilk %90\'ı zamanın %90\'ını alır. Son %10\'u diğer %90\'ını.',
        'Her zaman beklediğinden uzun sürer, bu kuralı hesaba katsan bile.',
        'Murphy iyimserdi.',
        'Ters gidebilecek her şey, genelde demo başlar başlamaz ters gider.',
        'Demo mutlaka bozulur. Tek soru, ne zaman.',
        'Her şey yolunda gidiyor gibi görünüyorsa, bir şeyi gözden kaçırmışsındır.',
        'Hızlı düzeltme diye bir şey yoktur.',
        'Yedekler, mutlu sonu seven insanlar içindir.',
        'Kullanıcı, senin varlığından haberin olmayan hatayı bulan kişidir.',
        'Hiçbir kod, hiç çalıştırılmayan kod kadar hızlı değildir.',
        'İnternet: "Google\'da ara" lafının hem tavsiye hem hakaret olduğu tek yer.',
        'Wi-Fi, yönlendiriciye yaklaştıkça daha iyi çalışan tek şeydir.',
        'Şifrelerini güvende tut, kahveni daha da güvende.',
        'Roma bir günde kurulmadı ama herhalde farklı bir framework kullanıyorlardı.',
        'Programlamak yemek yapmaya benzer: sık sık tat, ilk taslağı sunma.',
        'Makineler ne istediğini değil, ne söylediğini yapar.',
        'Meraklı ol. En iyi keşifler "hmm, bu garip" ile başlar.',
        'Bozuk değilse dokunma. Bozuksa da cuma günü dokunma.',
        'Umut bir yayına alma stratejisi değildir.',
        'Her uzmanın geçmişinde hatalar vardır. Hâlâ da var.',
        'Kod satırı sayısı ilerlemenin ölçüsü değildir, kilo ölçmüyorsan.',
        'En iyi arayüz, kimsenin fark etmediğidir.',
        'Bir gün bunların hepsi eski kod olacak.',
        'Kodun, bir yabancıya yazılmış mektuptur. Okunaklı yaz.',
        'Sadece teslim ettiğin özelliklerle değil, düzelttiğin hatalarla da gurur duy.',
        'Büyük işler, sıkıcı commit\'lerle tek tek inşa edilir.',
        'Su içmeyi unutma. Sen bir sunucu değilsin, soğutma sistemin yok.',
        'Nefes al. Sadece bir bilgisayar.',
        'Derlemelerin yeşil, kahven sert olsun.',
        'Kaynak seninle olsun.',
        'Yakında bir yabancıyla karşılaşacaksın. Yazıcısını tamir etmeni isteyecek.',
        'Hoş bir sürpriz seni bekliyor: hata bir yazım yanlışıymış.',
        'İyi haber: derleniyor. Kötü haber: derleniyor.',
        'Sabır, en iyi hata ayıklama aracıdır.',
        'Güzel bir çay, üç çözülmüş hata değerindedir.'
    ]
};
